version: 2
jobs:
  build:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make flavour="" all_comp
  build-install:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make flavour="--install" all_comp
  build-fast:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make flavour="--fast" all_comp
  build-test:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install build-essential
      - run: sudo apt-get -y install libelf-dev
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make flavour="--test" all_comp
workflows:
  version: 2
  caffe_builds:
    jobs:
      - build
      - build-install
      - build-fast
      - build-test

